services:
  frontend:
    build:
      context: ./frontend
      target: prod
      args:
        CONFIGURATION: production
    networks:
      - front-back-network
    ports:
      - '4200:4200'
    working_dir: /app
    depends_on:
      - backend


  backend:
    build:
      context: ./java_21
      target: production
    depends_on:
      - mysqldb
    restart: always
    networks:
      - spring-mysql-network
      - front-back-network
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: jdbc:mysql://mysqldb:3306/dockerDb?createDatabaseIfNotExist=true
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerDb
      MYSQL_USER: yvens
      MYSQL_PASSWORD: yvens_password
    working_dir: /app
  
  mysqldb:
    image: "mysql:8.2.0"
    volumes:
      - docker-mysql-volume:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    networks: 
      - spring-mysql-network
    environment:
      MYSQL_HOST: jdbc:mysql://localhost:3306/dockerDb?createDatabaseIfNotExist=true
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerDb
      MYSQL_USER: yvens
      MYSQL_PASSWORD: yvens_password
volumes:
  docker-mysql-volume:
networks:
  spring-mysql-network:
  front-back-network:
